package vetor;

import static org.junit.Assert.fail;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;


public class VetorTest {

    private Vetor<Integer> vetor;
    @Before
    public void setUp() throws Exception {
        this.vetor = new Vetor<Integer>(5);
    }

    @Test
    public void testInserir() {
        vetor.inserir(10);
        Assert.assertEquals(new Integer(10), vetor.procurar(10));
        
        vetor.inserir(10);
        Assert.assertEquals(new Integer(10), vetor.procurar(10));

        vetor.inserir(10);
        Assert.assertEquals(new Integer(10), vetor.procurar(10));

        vetor.inserir(10);
        Assert.assertEquals(new Integer(10), vetor.procurar(10));

        vetor.inserir(10);
        Assert.assertEquals(new Integer(10), vetor.procurar(10));

        try {
            vetor.inserir(10);
        }catch (Exception erro) {
            System.out.println(erro.getMessage());
        }
        
    }

    @Test
    public void testRemover() {
        fail("Not yet implemented");
    }

    @Test
    public void testProcurar() {
        fail("Not yet implemented");
    }

    @Test
    public void testIsVazio() {
        fail("Not yet implemented");
    }

    @Test
    public void testIsCheio() {
        fail("Not yet implemented");
    }

}
